image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS:   "4333796"

stages:
  - build
  - test

before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - rm -f  .gradle/caches/modules-2/modules-2.lock
#  - rm -fr .gradle/caches/*/plugin-resolution/
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
#    expire_in: 1 week

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

#instrumentationTests:
#  stage: test
#  tags:
#    - android # tag with which our runner is started
#  before_script:
#    - ''
#  image: shepeliev/android-sdk
#  script:
#    - /opt/start-default-emulator.sh
#    # Turn off animation
#    - adb shell settings put global window_animation_scale 0
#    - adb shell settings put global transition_animation_scale 0
#    - adb shell settings put global animator_duration_scale 0
#    # Turn off google auto-fill
#    - adb shell settings put secure autofill_service null
#    - ./gradlew cAT
#  only:
#    - /^master$/

after_script:
  - echo "End CI"